services:
  mongodb:
    image: mongo:latest
    container_name: ccmongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adm
      - MONGO_INITDB_ROOT_PASSWORD=ultraStrongPass321!
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: ccnode
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://adm:ultraStrongPass321!@mongodb:27017/carconfig?authSource=admin
    depends_on:
      - mongodb
    command: sh -c "node seed.js && node server.js"

volumes:
  mongo-data: